import pandas as pd
import joblib
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
import os # Used to interact with files

# --- Configuration ---
MODEL_DIR = "."  # The directory where models are stored
PRODUCTION_MODEL_FILE = os.path.join(MODEL_DIR, "airfare_model_pipeline.joblib")
CANDIDATE_MODEL_FILE = os.path.join(MODEL_DIR, "candidate_model.joblib")
NEW_DATA_FILE = "latest_airfare_data.csv" # This file would be generated by a separate process

# ===================================================================
#  STEP 1: FETCH LATEST DATA
# ===================================================================
def fetch_data():
    """
    In a real system, this function would connect to a database
    (e.g., BigQuery, Snowflake) and pull the last 3 months of data.
    For our example, it just reads a local CSV.
    """
    print(f"Fetching latest data from '{NEW_DATA_FILE}'...")
    try:
        df = pd.read_csv(NEW_DATA_FILE)
        return df
    except FileNotFoundError:
        print(f"Error: New data file '{NEW_DATA_FILE}' not found. Aborting.")
        return None

# ===================================================================
#  STEP 2: CLEAN & FEATURE ENGINEER
# ===================================================================
def preprocess_and_engineer(df):
    """
    This runs the *exact same* data preparation and feature engineering
    steps that we finalized in our notebook.
    """
    print("Running preprocessing and feature engineering...")
    
    # 1. Handle missing values (assuming same logic as before)
    #    ... (code for filling median/mode) ...
    
    # 2. Handle outliers (assuming same logic as before)
    #    ... (code for capping with IQR) ...
    
    # 3. Engineer new features (MUST match notebook)
    if 'airport_1' in df.columns and 'airport_2' in df.columns:
        df['route'] = df['airport_1'].astype(str) + '_' + df['airport_2'].astype(str)
    
    if 'Year' in df.columns and 'quarter' in df.columns:
        df['year_quarter'] = df['Year'].astype(str) + '_Q' + df['quarter'].astype(str)
    
    if 'large_ms' in df.columns and 'lf_ms' in df.columns:
        df['competition_ratio'] = df['large_ms'] / (df['lf_ms'] + 1e-6)
    
    print("Feature engineering complete.")
    return df

# ===================================================================
#  STEP 3: TRAIN NEW MODEL
# ===================================================================
def train_new_model(df):
    """
    Trains a new "candidate" model on the fresh data using the
    best parameters we found.
    """
    print("Training new candidate model...")
    
    # 1. Define features (X) and target (y)
    # This MUST match the final list from our notebook
    target_col = 'fare'
    cols_to_exclude = [
        target_col, 'fare_lg', 'fare_low', 'Geocoded_City1', 'Geocoded_City2',
        'citymarketid_1', 'citymarketid_2', 'airportid_1', 'airportid_2',
        'tbl', 'tbllapk', 'city1', 'city2', 'fare_per_mile'
    ]
    feature_cols = [col for col in df.columns if col not in cols_to_exclude and col in df.columns]
    
    numerical_features = df[feature_cols].select_dtypes(include='number').columns.tolist()
    categorical_features = df[feature_cols].select_dtypes(exclude='number').columns.tolist()
    
    y = df[target_col]
    X = df[feature_cols]

    # 2. Split data (we need a test set to evaluate this new model)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 3. Create the preprocessing pipeline (MUST match the original)
    numerical_transformer = StandardScaler()
    categorical_transformer = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numerical_transformer, numerical_features),
            ('cat', categorical_transformer, categorical_features)
        ],
        remainder='passthrough'
    )

    # 4. Get the best hyperparameters we found during tuning
    best_params = {
        'learning_rate': 0.1895,
        'max_depth': 9,
        'n_estimators': 221,
        'subsample': 0.7467
    }

    # 5. Create and train the final pipeline
    candidate_pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('model', XGBRegressor(**best_params, random_state=42, n_jobs=-1))
    ])
    
    candidate_pipeline.fit(X_train, y_train)
    print("Candidate model trained.")

    return candidate_pipeline, X_test, y_test

# ===================================================================
#  STEP 4: EVALUATE & PROMOTE (THE CRITICAL STEP)
# ===================================================================
def evaluate_and_promote(candidate_pipeline, X_test, y_test):
    """
    Compares the new model to the old one.
    Only if the new one is better does it get "promoted" to production.
    """
    print("Evaluating new model...")
    
    # 1. Get the new model's score
    y_pred_new = candidate_pipeline.predict(X_test)
    new_r2 = r2_score(y_test, y_pred_new)
    print(f"New candidate model R-squared: {new_r2:.4f}")

    # 2. Get the old (production) model's score on the SAME test set
    try:
        production_model = joblib.load(PRODUCTION_MODEL_FILE)
        y_pred_old = production_model.predict(X_test)
        old_r2 = r2_score(y_test, y_pred_old)
        print(f"Old production model R-squared: {old_r2:.4f}")
    except FileNotFoundError:
        print("No production model found. Promoting new model by default.")
        old_r2 = -1.0 # Set to a very low score
    except Exception as e:
        print(f"Error loading old model, will promote new model: {e}")
        old_r2 = -1.0

    # 3. The "Promotion" Logic
    if new_r2 > old_r2:
        print(f"New model is better ({new_r2:.4f} > {old_r2:.4f}). Promoting to production.")
        joblib.dump(candidate_pipeline, PRODUCTION_MODEL_FILE)
        print("Production model file has been overwritten.")
        
        # In a real system, this is where we would trigger the API
        # to restart and load the new model file.
        # e.g., trigger_api_restart()
        
    else:
        print(f"New model is not better ({new_r2:.4f} <= {old_r2:.4f}). Discarding.")

# ===================================================================
#  MAIN WORKFLOW
# ===================================================================
def main():
    print("--- Starting Automated Retraining Pipeline ---")
    
    # Step 1
    fresh_data = fetch_data()
    
    if fresh_data is not None:
        # Step 2
        processed_data = preprocess_and_engineer(fresh_data)
        
        # Step 3
        candidate, X_test, y_test = train_new_model(processed_data)
        
        # Step 4
        evaluate_and_promote(candidate, X_test, y_test)
    
    print("--- Pipeline run complete. ---")

if __name__ == "__main__":
    main()